### ISSUE TITLE
Hey Brother..I'm Nova Wahran

### ISSUE THREAD

**Issue by hellcatWahran** [alleguiemna/rest-api#1]
This is not an issue, I lost my fb account and this is the only way to contact u lol
Do u have a discord account??

**Comment by alleguiemna** [comment]
Hello brother,U are welcome I am sorry for your account facebook loose,i think  that u are blocked me But now no problem hhhhh Yeah i have discord send me your account i will add you 
    Le samedi 3 juillet 2021, 17:25:44 UTC+1, Danish ***@***.***> a écrit :  
 
 


This is not an issue, I lost my fb account and this is the only way to contact u lol
Do u have a discord account??

**Comment by hellcatWahran** [comment]
> Hello brother,U are welcome I am sorry for your account facebook loose,i think  that u are blocked me But now no problem hhhhh Yeah i have discord send me your account i will add you  Le samedi 3 juillet 2021, 17:25:44 UTC+1, Danish ***@***.***> a écrit : This is not an issue, I lost my fb account and this is the only way to contact u lol Do u have a discord account?? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

My discord username is : LucasNova#6933
You can send a friend request on discord or give me your discord username and i will send a request.
Btw, I had already send u friend request on fb, with a new account named - Danish Ansari
